#Configuration File for PlaytimeRewards@https://www.spigotmc.org/resources/100231/ by ExoBite

#This Option only Notifies you when a New Version is available, it doesn't download anything.
EnableUpdateCheck: true

#This Option downloads the latest Version of the Plugin and installs it upon a reboot.
AllowAutoUpdate: false

#The Amount of Players that get displayed by the Playtimetop-Command
PlaytimeTopAmount: 10

#Set to '-1' to Disable the Automatic Save Interval
DataSaveInterval: '1h30m'

#AFK-Block
AFK:
  #Enables or Disables the whole AFK-System.
  #When set to false, no other AFK-Value does anything.
  Enable: false

  #Here you can define, how much time needs to pass without an Action from the Player,
  #to flag the Player as AFK.
  Time: '10m'

  #Defines whether a Player Movement resets his AFK-Status
  CancelOnMove: true

  #Defines if a Players AFK-Status is reset by looking around
  CancelOnLook: true

  #Defines whether a Player Interaction resets his AFK-Status
  #(Interaction is any Sort of Right or Left Mouse Button Click)
  CancelOnInteract: true

  #Defines if Chatting resets the AFK-Status
  CancelOnChat: true

  #Defines if executing Commands resets the AFK-Status
  CancelOnCommand: true