name: PlaytimeRewards
main: com.github.exobite.mc.playtimerewards.main.PluginMaster
version: 0.1.2
author: ExoBiTe
description: This Plugin rewards players for their Playtime
api-version: 1.17

commands:
  Playtime:
    description: Display the players Playtime
    usage: /Playtime
    aliases: pt