name: PlaytimeRewards
main: com.github.exobite.mc.playtimerewards.main.PluginMaster
version: 0.1.2
author: ExoBiTe
website: https://www.spigotmc.org/resources/100231/
description: This Plugin rewards players for their Playtime
api-version: 1.17

commands:
  Playtime:
    description: Display the players Playtime
    usage: /Playtime [Player]
    aliases: pt

permissions:
  playtimerewards.*:
    description: Grants all Permissions
    default: op
    children:
      playtimerewards.notifyOnUpdate: true
      playtimerewards.cmd.playtime.other: true

  playtimerewards.notifyOnUpdate:
    description: Sends Update Notification upon Login
    default: op

  playtimerewards.cmd.playtime.own:
    description: Grants access to the /playtime command (can only see own playtime)

  playtimerewards.cmd.playtime.other:
    description: Grants access to the /playtime command (including seeing others playtime)
    default: op
    children:
      playtimerewards.cmd.playtime.own: true
