name: PlaytimeRewards
main: com.github.exobite.mc.playtimerewards.main.PluginMaster
version: 0.1.6
author: ExoBiTe
website: https://www.spigotmc.org/resources/100231/
description: This Plugin rewards players for their Playtime
api-version: 1.17
softdepend: [PlaceholderAPI]

commands:
  Playtime:
    description: Display the players Playtime
    usage: /Playtime [Player]
    aliases: pt
  Playtimetop:
    description: Displays the Players with the most Playtime
    usage: /Playtimetop
    aliases: pttop
  PlaytimeRewards:
    description: PlaytimeRewards Management Main Command
    usage: /Playtimerewatds
    aliases: ptr

permissions:
  playtimerewards.*:
    description: Grants all Permissions, excluding playtimerewards.afk.ignore
    default: op
    children:
      playtimerewards.notifyOnUpdate: true
      playtimerewards.cmd.playtime.other.offline: true
      playtimerewards.cmd.playtimetop: true
      playtimerewards.cmd.playtimerewards.*: true

  playtimerewards.notifyOnUpdate:
    description: Sends Update Notification upon Login
    default: op

  playtimerewards.cmd.playtime.own:
    description: Grants access to the /playtime command (can only see own playtime)

  playtimerewards.cmd.playtime.other:
    description: Grants access to the /playtime command (including seeing others playtime)
    default: op
    children:
      playtimerewards.cmd.playtime.own: true

  playtimerewards.cmd.playtime.other.offline:
    description: Grants access to the /playtime command (including seeing others playtime, even from offline players)
    default: op
    children:
      playtimerewards.cmd.playtime.other: true

  playtimerewards.cmd.playtimetop:
    description: Grants access to the /playtimetop command

  playtimerewards.cmd.playtimerewards.*:
    description: Grants full access to the /playtimerewards command
    default: op
    children:
      playtimerewards.cmd.playtimerewards.list: true
      playtimerewards.cmd.playtimerewards.editreward: true
      playtimerewards.cmd.playtimerewards.reload: true

  playtimerewards.cmd.playtimerewards.list:
    description: Grants access to the /playtimerewards list command

  playtimerewards.cmd.playtimerewards.editreward:
    description: Grants access to the /playtimerewards editReward command

  playtimerewards.cmd.playtimerewards.reload:
    description: Grants access to the /playtimerewards reload command

  playtimerewards.afk.ignore:
    description: Get never flagged as AFK with this Permission